apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
    argocd.argoproj.io/sync-wave: "1"
spec:
  zync:
    appSpec:
      replicas: 2
    queSpec:
      replicas: 2
