kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: system-searchd-manticore
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp4-csi #change
  volumeMode: Filesystem
