apiVersion: v1
kind: Secret
metadata:
  name: system-database
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
stringData:
  URL: "postgresql://admin3scale:redhat@operator-3scale-db.database.svc.cluster.local:5432/3scaleBD"
  #URL: "postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}"
type: Opaque
