apiVersion: v1
kind: Secret
metadata:
  name: zync
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
stringData:
  DATABASE_URL: "postgresql://admin3scale:redhat@operator-3scale-zync-db.database.svc.cluster.local:5432/zync_production"
  ZYNC_DATABASE_PASSWORD: "redhat"
  #DATABASE_URL: "postgresql://<zync-db-user>:<zync-db-password>@<zync-db-host>:<zync-db-port>/zync_production"
  #ZYNC_DATABASE_PASSWORD: "<zync-db-password>"
type: Opaque
