apiVersion: v1
kind: Secret
metadata:
  name: zync
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "0"
stringData:
  DATABASE_URL: "postgresql://adminzync:zy1ncpr4@LNXDBDVLI0015.gp.inet:5425/zync_production"
  ZYNC_DATABASE_PASSWORD: "zy1ncpr4"
  #DATABASE_URL: "postgresql://<zync-db-user>:<zync-db-password>@<zync-db-host>:<zync-db-port>/zync_production"
  #ZYNC_DATABASE_PASSWORD: "<zync-db-password>"
type: Opaque
