apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: 3scale-uat
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
    insecure_skip_verify: true
spec:
  username: admin
  systemMasterUrl: ""
  email: admin@ecorp.com
  organizationName: 3scale-uat
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale
  passwordCredentialsRef:
    name: uat-admin-secret
    namespace: 3scale
  tenantSecretRef:
    name: uat-tenant-secret #It is created automatically
    namespace: 3scale
    