apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: 3scale-dev
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
    insecure_skip_verify: true
spec:
  username: admin
  systemMasterUrl: ""
  email: admin@ecorp.com
  organizationName: 3scale-dev
  masterCredentialsRef:
    name: system-seed
    namespace: 3scale
  passwordCredentialsRef:
    name: dev-admin-secret
    namespace: 3scale
  tenantSecretRef:
    name: dev-tenant-secret #It is created automatically
    namespace: 3scale
    